version: '3.8'

services:
  postgres:
    image: postgres:16.4
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    network_mode: "host"

volumes:
  postgres-data:
