[package]
name = "sos24-use-case"
version.workspace = true
edition.workspace = true

[dependencies]
sos24-domain = { path = "../sos24-domain" }
anyhow.workspace = true
chrono.workspace = true
thiserror.workspace = true
uuid.workspace = true
url.workspace = true
