version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  postgres:
    image: postgres:14.13
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../.env

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ../.env

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    env_file:
      - ../.env
    depends_on:
      - mongo
    network_mode: service:app # devcontainer.jsonでポートフォワーディングするために必要

volumes:
  postgres-data:
  mongodb-data:
