version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # networks:
    #   - postgres-network
    #   - mongo-network
    ports:
      - 3000:3000
    env_file:
        - .env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  postgres:
    image: postgres:14.1
    restart: unless-stopped
    # networks:
    #   - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
        - .env

  mongo:
    image: mongo
    restart: always
    # networks:
    #   - mongo-network
    volumes:
      - mongodb-data:/data/db
    env_file:
        - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # networks:
    #   - mongo-network
    env_file:
        - .env
    depends_on:
      - mongo
    
# networks:
#   postgres-network:
#   mongo-network:

volumes:
  postgres-data:
  mongodb-data: