version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  postgres:
    image: postgres:16.4
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    env_file:
      - .env

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  postgres-data:
  mongodb-data: