openapi: "3.0.2"
info:
  title: Sohosai Online System
  version: "1.0"
servers:
  - url: http://localhost:3000
tags:
  - name: projects
    description: 企画関連の操作
  - name: users
    description: ユーザー関連の操作
  - name: news
    description: ニュース関連の操作
  - name: forms
    description: 申請関連の操作
  - name: form-answers
    description: 申請結果関連の操作
  - name: invitations
    description: 招待関連の操作
  - name: committee
    description: 実委人のみが利用可能

paths:
  /projects:
    $ref: "./schema/project.yml#/paths/~1projects"
  /projects/export:
    $ref: "./schema/project.yml#/paths/~1projects~1export"
  /projects/me:
    $ref: "./schema/project.yml#/paths/~1projects~1me"
  /projects/{project_id}:
    $ref: "./schema/project.yml#/paths/~1projects~1{project_id}"
  /projects/{project_id}/forms:
    $ref: "./schema/form.yml#/paths/~1projects~1{project_id}~1forms"
  /projects/{project_id}/forms/{form_id}/answer:
    $ref: "./schema/form-answer.yml#/paths/~1projects~1{project_id}~1forms~1{form_id}~1answer"
  /projects/{project_id}/news:
    $ref: "./schema/news.yml#/paths/~1projects~1{project_id}~1news"

  /users:
    $ref: "./schema/user.yml#/paths/~1users"
  /users/export:
    $ref: "./schema/user.yml#/paths/~1users~1export"
  /users/me:
    $ref: "./schema/user.yml#/paths/~1users~1me"
  /users/{user_id}:
    $ref: "./schema/user.yml#/paths/~1users~1{user_id}"

  /news:
    $ref: "./schema/news.yml#/paths/~1news"
  /news/{news_id}:
    $ref: "./schema/news.yml#/paths/~1news~1{news_id}"
  # TODO: ニュースの添付ファイル

  /invitations:
    $ref: "./schema/invitation.yml#/paths/~1invitations"
  /invitations/{invitation_id}:
    $ref: "./schema/invitation.yml#/paths/~1invitations~1{invitation_id}"

  /forms:
    $ref: "./schema/form.yml#/paths/~1forms"
  /forms/{form_id}:
    $ref: "./schema/form.yml#/paths/~1forms~1{form_id}"
  /forms/{form_id}/answers:
    $ref: "./schema/form-answer.yml#/paths/~1forms~1{form_id}~1answers"

components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Firebase Token
      in: header
      description: Firebaseのトークン
