paths:
  /project-application-period:
    get:
      operationId: getProjectApplicationPeriod
      summary: 企画募集期間を取得する
      tags:
        - projects
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/schemas/ProjectApplicationPeriod"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"

schemas:
  ProjectApplicationPeriod:
    type: object
    properties:
      start_at:
        type: string
        format: date-time
      end_at:
        type: string
        format: date-time
    required:
      - start_at
      - end_at
