paths:
  /projects:
    get:
      operationId: getProjects
      summary: 企画一覧の取得
      tags:
        - projects
        - committee
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/schemas/ProjectSummary"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
    post:
      operationId: postProject
      summary: 企画の作成
      tags:
        - projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/schemas/CreateProject"
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/schemas/CreatedProject"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"

  /projects/export:
    get:
      operationId: getProjectsExport
      summary: 企画一覧のエクスポート
      tags:
        - committee
      responses:
        200:
          description: OK
          content:
            text/csv:
              schema:
                type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"

  /projects/{project_id}:
    get:
      operationId: getProjectById
      summary: 特定のIDの企画の取得
      tags:
        - projects
        - committee
      parameters:
        - name: project_id
          in: path
          schema: { type: string }
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/schemas/Project"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
    put:
      operationId: putProjectById
      summary: 特定のIDの企画の更新
      tags:
        - projects
        - committee
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/schemas/UpdateProject"
      responses:
        200:
          description: OK
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
    delete:
      operationId: deleteProjectById
      summary: 特定のIDの企画の削除
      tags:
        - projects
        - committee
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"

  /projects/me:
    get:
      operationId: getMyProject
      summary: 自分が企画責任者・副企画責任者になっている企画の取得
      tags:
        - projects
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/schemas/Project"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "./error.yml#/schemas/Error"

components:
  ProjectCategory:
    type: string
    enum:
      - general
      - foods_with_kitchen
      - foods_without_kitchen
      - foods_without_cooking
      - stage_1a
      - stage_university_hall
      - stage_united

  ProjectAttribute:
    type: string
    enum:
      - "academic"
      - "art"
      - "official"
      - "inside"
      - "outside"

schemas:
  ProjectSummary:
    type: object
    properties:
      id:
        type: string
        format: uuid
      index:
        type: integer
        example: 0
      title:
        type: string
        example: そぽたん焼き
      category:
        $ref: "#/components/ProjectCategory"
      attributes:
        type: array
        items:
          $ref: "#/components/ProjectAttribute"
      owner_id:
        type: string
        format: uuid
      owner_name:
        type: string
      owner_email:
        type: string
        format: email
    required:
      - id
      - index
      - title
      - category
      - attributes
      - owner_id
      - owner_name
      - owner_email
  Project:
    type: object
    properties:
      id:
        type: string
        format: uuid
      index:
        type: integer
        example: 0
      title:
        type: string
        example: そぽたん焼き
      kana_title:
        type: string
        example: そぽたんやき
      group_name:
        type: string
        example: そぽたん愛好会
      kana_group_name:
        type: string
        example: そぽたんあいこうかい
      category:
        $ref: "#/components/ProjectCategory"
      attributes:
        type: array
        items:
          $ref: "#/components/ProjectAttribute"
      owner_id:
        type: string
        format: uuid
      owner_name:
        type: string
      owner_email:
        type: string
      sub_owner_id:
        type: string
        format: uuid
      sub_owner_name:
        type: string
      sub_owner_email:
        type: string
      remarks:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      deleted_at:
        type: string
        format: date-time
    required:
      - id
      - index
      - title
      - kana_title
      - group_name
      - kana_group_name
      - category
      - attributes
      - owner_id
      - owner_name
      - owner_email
      - created_at
      - updated_at
  CreateProject:
    type: object
    properties:
      title:
        type: string
        example: そぽたん焼き
      kana_title:
        type: string
        example: そぽたんやき
      group_name:
        type: string
        example: そぽたん愛好会
      kana_group_name:
        type: string
        example: そぽたんあいこうかい
      category:
        $ref: "#/components/ProjectCategory"
      attributes:
        type: array
        items:
          $ref: "#/components/ProjectAttribute"
    required:
      - title
      - kana_title
      - group_name
      - kana_group_name
      - category
      - attributes
  UpdateProject:
    type: object
    properties:
      title:
        type: string
        example: そぽたん焼き
      kana_title:
        type: string
        example: そぽたんやき
      group_name:
        type: string
        example: そぽたん愛好会
      kana_group_name:
        type: string
        example: そぽたんあいこうかい
      category:
        $ref: "#/components/ProjectCategory"
        example: foods_with_kitchen
      attributes:
        type: array
        items:
          $ref: "#/components/ProjectAttribute"
      remarks:
        type: string
    required:
      - title
      - kana_title
      - group_name
      - kana_group_name
      - category
      - attributes
  CreatedProject:
    type: object
    properties:
      id:
        type: string
        format: uuid
    required:
      - id