name: Rust

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, portainer]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        env:
          SQLX_OFFLINE: true
        run: cargo build --verbose
      - name: Run tests
        env:
          SQLX_OFFLINE: true
        run: cargo test --verbose