name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Test Secrets
        run: |
          echo secret "${{secrets.PORTAINER_URL }}" | sed 's/./& /g'
      - name: Build
        env:
          SQLX_OFFLINE: true
        run: cargo check --verbose --locked
      - name: Run tests
        env:
          SQLX_OFFLINE: true
        run: cargo test --verbose --locked
