name: Rust

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, portainer]
    steps:
      - uses: actions/checkout@v4
      - name: Symlink
        run: ln -s $GITHUB_WORKSPACE /home/runner/work/$GITHUB_REPO/$GITHUB_REPO
      - name: ubuntu mirror
        run: sudo sed -i.bak -r 's@http://(jp\.)?archive\.ubuntu\.com/ubuntu/?@https://ftp.udx.icscoe.jp/Linux/ubuntu/@g' /etc/apt/sources.list
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        env:
          SQLX_OFFLINE: true
        run: cargo build --verbose
      - name: Run tests
        env:
          SQLX_OFFLINE: true
        run: cargo test --verbose