name: Rust

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: [self-hosted, hayabusa]
    steps:
      - uses: actions/checkout@v4
      - name: Symlink
        run: mkdir -p /home/runner/work/${{ github.event.repository.name }}/ && ln -s ${{ github.workspace }} /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: ubuntu mirror
        run: sudo sed -i.bak -r 's@http://(jp\.)?archive\.ubuntu\.com/ubuntu/?@https://ftp.udx.icscoe.jp/Linux/ubuntu/@g' /etc/apt/sources.list
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy rustfmt
      - name: Cache dependencies
        id: cache
        uses: corca-ai/local-cache@v2
        with:
          path: target
          key: ${{ hashFiles('Cargo.lock') }}
      - name: Format
        run: cargo fmt --all --check
      - name: Clippy
        uses: sksat/action-clippy@v0.8.0
        if: github.event_name == 'pull_request'
        env:
          SQLX_OFFLINE: true
        with:
          reporter: github-pr-review
      - name: Run tests
        env:
          SQLX_OFFLINE: true
        run: cargo test --verbose
